### ISSUE TITLE
Cannot display multiple map components on the same page

### ISSUE THREAD

**Issue by pugun** [phamtung1/react-google-map-picker#3]
when I try to do this 
![image](https://user-images.githubusercontent.com/25225071/90748994-1418e300-e2fd-11ea-8161-98b2792c0d34.png)

to show 2 map picker components on the same page. It only display the first one and the second one is blank like this
![image](https://user-images.githubusercontent.com/25225071/90748346-4413b680-e2fc-11ea-81b2-602a9463efc9.png)
any idea how to solve this. thank you in advance

The error says "You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors."

**Comment by phamtung1** [comment]
hi @pugun , sorry for the late reply. I think the bug has been fixed in version 1.2.2. But this version uses react 17. If you can not use it, I can create another fix for react 16. Thanks!
